name: xcalc-tests
channels:
    - conda-forge
    - nodefaults
dependencies:
    - dask
    - xarray
    - numpy
    - xclim
    - netCDF4
    - pytest
    - pytest-cov
    - pytest-env
    - pooch
    - pint<0.24

    - pip:
      - pyhomogenize>=0.5.1
